Repository NVIDIA-Merlin/NVTabular, pull requests merged in 2020-06, with the labels that each got.

#77 [REVIEW] Add CSVDatasetEngine for DaskDataset
  nvtabular/dask/io.py
  tests/unit/test_dask_nvt.py
Labels: IO, MultiGPU

#67 [REVIEW] Add Dropna() operation in ops.py
  docs/source/api/ops/dropna.rst
  docs/source/api/ops/index.rst
  nvtabular/ops.py
  tests/unit/test_ops.py
Labels: Outbrains

#90 [REVIEW] Handle single file input in ParquetDatasetEngine
  nvtabular/dask/io.py
  tests/unit/test_io.py
Labels: IO, MultiGPU, bug

#91 [REVIEW] Fix dask-based categorify logic for frequency-limited encoding
  nvtabular/dask/categorify.py
  tests/unit/test_dask_nvt.py
Labels: MultiGPU, bug

#105 [REVIEW] Avoid future pyarrow deprecation problems
  nvtabular/dask/io.py
Labels: IO, MultiGPU
