Repository NVIDIA-Merlin/NVTabular, pull requests merged in 2021-12, with the labels that each got.

#1259 Reduce device-memory footprint in Categorify fit
  nvtabular/ops/categorify.py
  tests/unit/ops/test_categorify.py
Labels: bug, Perf

#1312 Fix Triton import for `_convert_string2pytorch_dtype`
  nvtabular/inference/triton/__init__.py
Labels: bug

#1339 Triton setup via merlin graph api
  nvtabular/graph/node.py
  nvtabular/graph/schema.py
  nvtabular/inference/graph/ensemble.py
  nvtabular/inference/graph/graph.py
  nvtabular/inference/graph/node.py
  nvtabular/inference/graph/ops/operator.py
  nvtabular/inference/graph/ops/tensorflow.py
  nvtabular/inference/graph/ops/workflow.py
  nvtabular/inference/triton/ensemble.py
  tests/unit/inference/__init__.py
  tests/unit/inference/inference_utils.py
  tests/unit/inference/test_ensemble.py
  tests/unit/inference/test_export.py
  tests/unit/inference/test_graph.py
  tests/unit/inference/test_inference_ops.py
  tests/unit/inference/test_op_runner.py
  tests/unit/inference/test_tensorflow_inf_op.py
Labels: enhancement
