Repository NVIDIA-Merlin/NVTabular, pull requests merged in 2021-11, with the labels that each got.

#1223 Resolve Categorify and to_parquet performance regressions
  nvtabular/io/dataset.py
  nvtabular/ops/categorify.py
  tests/unit/ops/test_categorify.py
  tests/unit/test_io.py
Labels: IO, Perf

#1239 Avoid copy of remote-data buffer in call to read_parquet
  nvtabular/io/fsspec_utils.py
Labels: bug, IO, Perf

#1270 Remove non-exist Torch `uint` dtypes from Triton conversion utils
  nvtabular/inference/triton/ensemble.py
Labels: bug

#1256 End-to-end Inference support for Transformers4Rec Tensorflow Models
  nvtabular/inference/triton/ensemble.py
  nvtabular/inference/triton/runners/tensorflow.py
  tests/unit/test_triton_inference.py
Labels: TensorFlow, Inference, session-based
