Repository NVIDIA-Merlin/NVTabular, pull requests merged in 2021-06, with the labels that each got.

#850 Adding map function to KerasSequenceLoader
  nvtabular/loader/tensorflow.py
  tests/unit/test_tf_dataloader.py
Labels: TensorFlow

#885 Remove ML frameworks from conda environments
  conda/environments/nvtabular_dev_cuda10.1.yml
  conda/environments/nvtabular_dev_cuda10.2.yml
  conda/environments/nvtabular_dev_cuda11.0.yml
  conda/environments/nvtabular_dev_cuda11.2.yml
Labels: dependencies

#903 Fix `Categorify` output dtypes for list columns
  nvtabular/dispatch.py
  nvtabular/ops/categorify.py
  tests/unit/test_ops.py
Labels: bug
