Repository NVIDIA-Merlin/NVTabular, pull requests merged in 2021-09, with the labels that each got.

#1093 [HELP-REQ] Add tests for issue #1074 and update Categorify args
  nvtabular/ops/categorify.py
  tests/unit/ops/test_ops.py
Labels: help wanted, WIP

#1081 Update and Improve ParquetDatasetEngine
  nvtabular/io/dataset.py
  nvtabular/io/dataset_engine.py
  nvtabular/io/parquet.py
  tests/unit/test_io.py
Labels: bug, enhancement, MultiGPU, IO

#1129 Avoid using cudf.read_parquet on the client process
  nvtabular/io/parquet.py
  nvtabular/ops/categorify.py
Labels: MultiGPU, IO, Perf
