Repository NVIDIA-Merlin/NVTabular, pull requests merged in 2022-11, with the labels that each got.

#1694 Use merlin-dataloader package
  bench/examples/dataloader_bench.py
  bench/torch/criteo/criteo-example-basedl.ipynb
  bench/torch/criteo/criteo-example-iterdl.ipynb
  bench/torch/criteo/criteo-example-nvtdl.ipynb
  bench/torch/criteo/criteo-example-petastorm.ipynb
  nvtabular/loader/__init__.py
  nvtabular/loader/backend.py
  nvtabular/loader/tensorflow.py
  nvtabular/loader/torch.py
  requirements/base.txt
  tests/unit/loader/test_dataloader_backend.py
  tests/unit/loader/test_tf_dataloader.py
  tests/unit/loader/test_torch_dataloader.py
  tox.ini
Labels: chore

#1696 Upload binary wheels for nvtabular
  .github/workflows/cpu-ci.yml
Labels: ci

#1697 docs: Add basic SEO configuration
  docs/source/conf.py
Labels: documentation

#1699 docs: Add semver to calver banner
  docs/source/_static/css/custom.css
  docs/source/_templates/layout.html
  docs/source/conf.py
Labels: documentation

#1703 Update metrics keys in example notebook tests
  tests/unit/examples/test_01-Getting-started.py
  tests/unit/examples/test_02-Advanced-NVTabular-workflow.py
  tox.ini
Labels: bug, examples

#1710 fix tox to use correct branch in release tags
  .github/workflows/cpu-ci.yml
  tox.ini
Labels: bug, ci, chore

#1702 Add Jenkinsfile
  ci/pr.gpu.Jenkinsfile
Labels: ci, chore, gpuCI-test-this

#1712 Release draft fix
  .github/workflows/release-drafter.yaml
Labels: ci, chore

#1704 chore: Reduce repo size and update build actions
  .github/workflows/blossom-ci.yml
  .github/workflows/conda-env-create.yml
  .github/workflows/cpu-ci.yml
  .github/workflows/docs-preview-pr.yaml
  .github/workflows/docs-remove-stale-reviews.yaml
  .github/workflows/docs-sched-rebuild.yaml
  docs/source/conf.py
Labels: skip-changelog, chore
