Repository NVIDIA-Merlin/NVTabular, pull requests merged in 2022-08, with the labels that each got.

#1651 Update `versioneer` from 0.19 to 0.23
  nvtabular/__init__.py
  nvtabular/_version.py
  versioneer.py
Labels: ci, chore

#1641 Update the `Categorify` operator to set the domain max correctly
  nvtabular/ops/categorify.py
  nvtabular/ops/drop_low_cardinality.py
  tests/unit/ops/test_ops_schema.py
Labels: bug

#1609 Extract Python and Dask `Executor` classes from `Workflow`
  nvtabular/workflow/executor.py
  nvtabular/workflow/workflow.py
Labels: chore

#1655 Fix typos
  ci/ignore_codespell_words.txt
  examples/multi-gpu-toy-example/multi-gpu_dask.ipynb
  examples/scaling-criteo/02-ETL-with-NVTabular.ipynb
  examples/tensorflow/TFRecords-To-Parquet.ipynb
  nvtabular/ops/categorify.py
Labels: documentation

#1654 Fix groupby on lists with cudf 22.06+
  nvtabular/ops/groupby.py
Labels: bug

#1656 Replace cudf series ceil() with numpy ceil()
  nvtabular/tools/data_gen.py
Labels: ci, breaking

#1657 Remove using-feature-columns nb
  examples/tensorflow/using-feature-columns.ipynb
Labels: examples, chore

#1659 Update black/pylint/flake8,isort etc
  .pre-commit-config.yaml
  .pylintrc
  bench/datasets/test_dataset.py
  bench/examples/MultiGPUBench.md
  bench/examples/dataloader_bench.py
  bench/torch/criteo/criteo-example-basedl.ipynb
  bench/torch/criteo/criteo-example-iterdl.ipynb
  bench/torch/criteo/criteo-example-nvtdl.ipynb
  bench/torch/criteo/criteo-example-petastorm.ipynb
  examples/multi-gpu-movielens/torch_trainer_dist.py
  nvtabular/__init__.py
  nvtabular/framework_utils/tensorflow/__init__.py
  nvtabular/framework_utils/tensorflow/feature_column_utils.py
  nvtabular/framework_utils/tensorflow/layers/__init__.py
  nvtabular/framework_utils/tensorflow/layers/embedding.py
  nvtabular/inference/triton/__init__.py
  nvtabular/inference/triton/benchmarking_tools.py
  nvtabular/inference/triton/ensemble.py
  nvtabular/inference/workflow/hugectr.py
  nvtabular/loader/backend.py
  nvtabular/loader/tf_utils.py
  nvtabular/loader/torch.py
  nvtabular/ops/__init__.py
  nvtabular/ops/add_metadata.py
  nvtabular/ops/bucketize.py
  nvtabular/ops/categorify.py
  nvtabular/ops/clip.py
  nvtabular/ops/column_similarity.py
  nvtabular/ops/data_stats.py
  nvtabular/ops/difference_lag.py
  nvtabular/ops/drop_low_cardinality.py
  nvtabular/ops/dropna.py
  nvtabular/ops/fill.py
  nvtabular/ops/filter.py
  nvtabular/ops/groupby.py
  nvtabular/ops/hash_bucket.py
  nvtabular/ops/hashed_cross.py
  nvtabular/ops/join_external.py
  nvtabular/ops/join_groupby.py
  nvtabular/ops/lambdaop.py
  nvtabular/ops/list_slice.py
  nvtabular/ops/logop.py
  nvtabular/ops/moments.py
  nvtabular/ops/normalize.py
  nvtabular/ops/reduce_dtype_size.py
  nvtabular/ops/rename.py
  nvtabular/ops/stat_operator.py
  nvtabular/ops/target_encoding.py
  nvtabular/ops/value_counts.py
  nvtabular/workflow/__init__.py
  requirements-dev.txt
  tests/integration/common/parsers/criteo_parsers.py
  tests/integration/test_rossman.py
  tests/unit/loader/test_torch_dataloader.py
  tests/unit/ops/test_reduce_dtype_size.py
  tests/unit/test_triton_inference.py
Labels: chore

#1660 Fix integration tests that reached into `Workflow`'s private methods
  nvtabular/workflow/executor.py
  nvtabular/workflow/workflow.py
  tests/integration/test_movielens.py
  tests/integration/test_nvt_hugectr.py
  tests/integration/test_rossman.py
Labels: bug, ci

#1661 Fix dl
  nvtabular/loader/backend.py
Labels: ci, dataloader, breaking

#1663 Add `scipy` as a dependency
  requirements.txt
Labels: dependencies, ci, chore

#1664 Add optional requirement specifiers for GPU and dev requirements
  MANIFEST.in
  requirements-dev.txt
  setup.py
Labels: dependencies, ci, clean up, chore
