Repository NVIDIA-Merlin/NVTabular, pull requests merged in 2022-09, with the labels that each got.

#1668 Remove FastAI notebooks
  bench/datasets/tools/train_pytorch.py
  bench/examples/gpu_benchmark.ipynb
  docs/source/toc.yaml
  examples/scaling-criteo/03-Training-with-FastAI.ipynb
  examples/scaling-criteo/README.md
  examples/tabular-data-rossmann/03-Training-with-FastAI.ipynb
  examples/tabular-data-rossmann/README.md
  nvtabular/framework_utils/torch/utils.py
  tests/integration/common/parsers/benchmark_parsers.py
  tests/integration/common/parsers/criteo_parsers.py
  tests/integration/common/parsers/rossmann_parsers.py
  tests/integration/test_criteo.py
  tests/integration/test_rossman.py
  tests/unit/test_notebooks.py
Labels: breaking

#1667 Set up `tox` environments for testing, linting, and building docs
  .github/workflows/cpu-ci.yml
  .github/workflows/docs-sched-rebuild.yaml
  MANIFEST.in
  docs/Makefile
  requirements-dev.txt
  requirements/base.txt
  requirements/dev.txt
  requirements/docs.txt
  requirements/gpu.txt
  requirements/test.txt
  setup.py
  tox.ini
Labels: ci, clean up, chore

#1671 Use the latest version of Merlin Core from `main` in the `tox` test envs
  tox.ini
Labels: ci, chore

#1666 Switch to using the DAG executors from Merlin Core
  nvtabular/workflow/executor.py
  nvtabular/workflow/workflow.py
  requirements-test.txt
Labels: clean up, chore

#1673 Remove poetry config
  poetry.lock
  pyproject.toml
Labels: dependencies

#1677 Use Merlin DAG executors from core in integration tests
  tests/integration/test_movielens.py
  tests/integration/test_nvt_hugectr.py
  tests/integration/test_rossman.py
Labels: bug, ci

#1674 Remove stray file left over from Torch/Horovod multi-GPU example
  examples/multi-gpu-movielens/torch_trainer_dist.py
Labels: clean up, chore

#1669 Remove examples Part 1 - Rossmann, RecSys2020, Outbrain
  ci/test_integration.sh
  docs/source/resources/architecture.md
  docs/source/toc.yaml
  docs/source/training/tensorflow.rst
  examples/README.md
  examples/advanced-ops-outbrain/01-Download-Convert.ipynb
  examples/advanced-ops-outbrain/02-ETL-with-NVTabular.ipynb
  examples/advanced-ops-outbrain/03-Training-with-TF.ipynb
  examples/advanced-ops-outbrain/README.md
  examples/tabular-data-rossmann/01-Download-Convert.ipynb
  examples/tabular-data-rossmann/02-ETL-with-NVTabular.ipynb
  examples/tabular-data-rossmann/03-Training-with-PyTorch.ipynb
  examples/tabular-data-rossmann/03-Training-with-TF.ipynb
  examples/tabular-data-rossmann/README.md
  examples/winning-solution-recsys2020-twitter/01-02-04-Download-Convert-ETL-with-NVTabular-Training-with-XGBoost.ipynb
  tests/integration/test_rossman.py
  tests/unit/test_notebooks.py
Labels: examples

#1633 update NVTabular examples
  examples/01-Getting-started.ipynb
  examples/02-Advanced-NVTabular-workflow.ipynb
  examples/03-Running-on-multiple-GPUs-or-on-CPU.ipynb
  examples/imgs/dask-dataframe.svg
  requirements-test.txt
  requirements/test.txt
  tests/conftest.py
  tests/unit/examples/test_01-Getting-started.py
  tests/unit/examples/test_02-Advanced-NVTabular-workflow.py
  tests/unit/examples/test_03-Running-on-multiple-GPUs-or-on-CPU.py
Labels: documentation, examples
