Repository NVIDIA-Merlin/NVTabular, pull requests merged in 2022-07, with the labels that each got.

#1598 Groupby to no longer require groupby_cols in column selector
  nvtabular/ops/groupby.py
  tests/unit/ops/test_groupyby.py
Labels: bug

#1608 Don't install tests with nvtabular
  setup.py
Labels: bug

#1610 Don't `git pull origin main` in integration tests, use container version
  ci/test_integration.sh
Labels: chore

#1616 fix ci script for integration tests and added skip check
  .github/workflows/cpu-ci.yml
  ci/test_integration.sh
  tests/integration/test_nvt_hugectr.py
Labels: ci, chore

#1617 Remove unnecessary docs dependencies
  docs/source/conf.py
  requirements-dev.txt
Labels: chore

#1619 fix tritonserver gpu id & fixed timeout for criteo integration tests
  tests/integration/test_criteo.py
  tests/integration/test_nvt_hugectr.py
Labels: ci, chore

#1620 skip download step, that is not allowed in CI
  tests/integration/test_movielens.py
  tests/integration/test_rossman.py
Labels: ci, chore

#1622 Fix movielens notebook data path
  examples/getting-started-movielens/01-Download-Convert.ipynb
  tests/integration/test_rossman.py
Labels: ci, chore

#1623 Tri up time
  tests/conftest.py
Labels: ci, chore

#1627 Inference Integration test fix
  tests/integration/test_movielens.py
Labels: ci, chore

#1628 Fix PyTorch export/serving with Python back-end for T4R notebooks
  nvtabular/inference/triton/__init__.py
  nvtabular/inference/triton/ensemble.py
  nvtabular/inference/triton/model/model_pt.py
  nvtabular/inference/triton/workflow_model.py
  nvtabular/inference/workflow/pytorch.py
Labels: bug, PyTorch, Inference

#1631 Increase rossmann integration test threshold
  tests/integration/test_rossman.py
Labels: chore

#1634 Test LambdaOp with dask workflows
  nvtabular/ops/lambdaop.py
  tests/unit/test_dask_nvt.py
Labels: bug

#1638 Add sum to supported aggregations in Groupby
  nvtabular/ops/groupby.py
  tests/unit/ops/test_groupyby.py
Labels: enhancement
