Repository NVIDIA-Merlin/NVTabular, pull requests merged in 2022-04, with the labels that each got.

#1494 Note in the README that installing with pip runs only on CPU
  README.md
Labels: documentation

#1492 Add deprecation warnings to `loader`, `inference`, `framework_utils`
  nvtabular/framework_utils/__init__.py
  nvtabular/inference/__init__.py
  nvtabular/loader/__init__.py
Labels: documentation

#1497 fix for 1455
  examples/tabular-data-rossmann/03-Training-with-TF.ipynb
Labels: bug

#1496 Restrict running on pandas 1.4.x
  requirements.txt
Labels: dependencies

#1500 Fixing Criteo Inference for TensorFlow and HugeCTR
  examples/scaling-criteo/04-Triton-Inference-with-HugeCTR.ipynb
  examples/scaling-criteo/04-Triton-Inference-with-TF.ipynb
Labels: bug

#1508 added category name to domain for column properties
  nvtabular/ops/categorify.py
  nvtabular/ops/drop_low_cardinality.py
  tests/unit/ops/test_categorify.py
Labels: enhancement

#1513 Max auc
  tests/integration/common/parsers/criteo_parsers.py
Labels: enhancement
