Repository NVIDIA-Merlin/NVTabular, pull requests merged in 2022-06, with the labels that each got.

#1577 Use shared implementation of triage workflow
  .github/workflows/triage.yml
Labels: ci

#1579 Add a GA workflow that requires labels on PR's
  .github/workflows/require-label.yaml
Labels: ci

#1581 Merlin offers three containers
  .pre-commit-config.yaml
  README.md
  examples/README.md
  examples/getting-started-movielens/04-Triton-Inference-with-HugeCTR.ipynb
  examples/getting-started-movielens/04-Triton-Inference-with-TF.ipynb
  examples/scaling-criteo/docker-compose-fastai.yml
  examples/scaling-criteo/docker-compose-hugectr.yml
  examples/scaling-criteo/docker-compose-tf.yml
Labels: documentation

#1585 Update poetry config
  poetry.lock
  pyproject.toml
Labels: dependencies

#1588 Update the container labels in the integration tests
  ci/test_integration.sh
  tests/integration/test_notebooks.py
Labels: ci

#1591 Update URLs to Criteo datasets
  examples/scaling-criteo/01-Download-Convert.ipynb
  examples/tensorflow/accelerating-tensorflow.ipynb
Labels: documentation

#1580 add casting for additional aggs in groupby
  nvtabular/ops/groupby.py
  tests/unit/ops/test_groupyby.py
Labels: bug

#1594 Fix integration tests
  ci/test_integration.sh
Labels: ci

#1587 cast to string
  nvtabular/loader/tf_utils.py
Labels: bug

#1528 docs: Add TF compat info
  docs/source/resources/troubleshooting.md
  examples/README.md
Labels: documentation, examples

#1592 column names can now include aggregations in ops.Groupby
  nvtabular/ops/groupby.py
  tests/unit/ops/test_groupyby.py
Labels: bug
