Repository NVIDIA-Merlin/NVTabular, pull requests merged in 2022-03, with the labels that each got.

#1419 Update `merlin-core` to `v0.1.1` (instead of `main` branch)
  ci/build_and_test.sh
  requirements.txt
Labels: dependencies

#1420 Assume 'merlin' is a first party package for isort
  nvtabular/framework_utils/tensorflow/feature_column_utils.py
  nvtabular/inference/graph/ensemble.py
  nvtabular/inference/graph/ops/operator.py
  nvtabular/inference/graph/ops/tensorflow.py
  nvtabular/inference/graph/ops/workflow.py
  nvtabular/inference/triton/data_conversions.py
  nvtabular/inference/triton/ensemble.py
  nvtabular/inference/workflow/base.py
  nvtabular/loader/backend.py
  nvtabular/loader/tensorflow.py
  nvtabular/ops/bucketize.py
  nvtabular/ops/categorify.py
  nvtabular/ops/column_similarity.py
  nvtabular/ops/difference_lag.py
  nvtabular/ops/groupby.py
  nvtabular/ops/hash_bucket.py
  nvtabular/ops/join_external.py
  nvtabular/ops/join_groupby.py
  nvtabular/ops/list_slice.py
  nvtabular/ops/logop.py
  nvtabular/ops/normalize.py
  nvtabular/ops/operator.py
  nvtabular/ops/reduce_dtype_size.py
  nvtabular/ops/target_encoding.py
  nvtabular/tools/data_gen.py
  nvtabular/tools/dataset_inspector.py
  nvtabular/workflow/node.py
  nvtabular/workflow/workflow.py
  pyproject.toml
  tests/conftest.py
  tests/unit/framework_utils/test_tf_feature_columns.py
  tests/unit/inference/test_ensemble.py
  tests/unit/inference/test_graph.py
  tests/unit/inference/test_inference_ops.py
  tests/unit/inference/test_op_runner.py
  tests/unit/loader/test_torch_dataloader.py
  tests/unit/ops/test_categorify.py
  tests/unit/ops/test_groupyby.py
  tests/unit/ops/test_lambda.py
  tests/unit/ops/test_ops.py
  tests/unit/test_tf4rec.py
  tests/unit/test_triton_inference.py
  tests/unit/workflow/test_workflow.py
  tests/unit/workflow/test_workflow_chaining.py
  tests/unit/workflow/test_workflow_node.py
  tests/unit/workflow/test_workflow_ops.py
  tests/unit/workflow/test_workflow_schemas.py
Labels: dependencies

#1391 End-to-end inference POC migration to new ensemble API
  nvtabular/inference/graph/ensemble.py
  nvtabular/inference/graph/node.py
  nvtabular/inference/graph/ops/faiss.py
  nvtabular/inference/graph/ops/feast.py
  nvtabular/inference/graph/ops/operator.py
  nvtabular/inference/graph/ops/session_filter.py
  nvtabular/inference/graph/ops/softmax_sampling.py
  nvtabular/inference/graph/ops/tensorflow.py
  nvtabular/inference/graph/ops/unroll_features.py
  nvtabular/inference/graph/ops/workflow.py
  nvtabular/inference/triton/ensemble.py
  nvtabular/inference/triton/oprunner_model.py
  nvtabular/loader/backend.py
  nvtabular/ops/categorify.py
  nvtabular/ops/groupby.py
  nvtabular/workflow/workflow.py
  tests/unit/inference/test_ensemble.py
  tests/unit/inference/test_ensemble_ops.py
  tests/unit/inference/test_graph.py
  tests/unit/inference/test_inference_ops.py
  tests/unit/inference/test_tensorflow_inf_op.py
  tests/unit/loader/test_dataloader_backend.py
  tests/unit/loader/test_tf_dataloader.py
  tests/unit/loader/test_torch_dataloader.py
  tests/unit/test_dask_nvt.py
  tests/unit/test_tf4rec.py
  tests/unit/workflow/test_workflow_node.py
  tests/unit/workflow/test_workflow_schemas.py
Labels: enhancement

#1425 Fix lambda dtype issue in PyTorch Multi-GPU training example notebook
  examples/multi-gpu-movielens/01-03-MultiGPU-Download-Convert-ETL-with-NVTabular-Training-with-PyTorch.ipynb
Labels: bug

#1430 Fix dtype bug with GroupBy operator when `aggs` is a string
  nvtabular/ops/groupby.py
  tests/unit/ops/test_groupyby.py
Labels: bug

#1414 Add TagAs and related wrapper classes
  nvtabular/ops/__init__.py
  nvtabular/ops/add_metadata.py
  tests/unit/ops/test_ops_schema.py
Labels: enhancement

#1462 Wrapper for TagAs did not work
  nvtabular/ops/add_metadata.py
Labels: bug

#1454 Set up automated docstring coverage checks
  .github/workflows/cpu-ci.yml
  .pre-commit-config.yaml
  pyproject.toml
  requirements-dev.txt
Labels: documentation

#1450 doc: Update matrix for 22.03
  docs/source/resources/support_matrix.rst
Labels: documentation

#1453 Fix bug about criteo download notebook
  examples/scaling-criteo/01-Download-Convert.ipynb
Labels: bug

#1468 Hard-code the `Workflow` output dtypes for HugeCTR in Triton
  nvtabular/inference/triton/workflow_model.py
Labels: bug

#1421 AWS SageMaker
  conda/environments/nvtabular_aws_sagemaker.yml
  docs/source/resources/cloud_integration.md
Labels: documentation

#1465 Improve `Workflow` error about mismatched dtypes
  nvtabular/workflow/workflow.py
Labels: documentation

#1471 Exclude additional directories and boost docstring coverage req to 35 percent
  pyproject.toml
Labels: documentation

#1476 Add missing `--user` flag to `natsort` CI install
  ci/build_and_test.sh
  requirements-dev.txt
Labels: bug, ci

#1487 Remove imports to deprecated modules
  nvtabular/__init__.py
  nvtabular/loader/tf_utils.py
  nvtabular/ops/categorify.py
  nvtabular/ops/drop_low_cardinality.py
  nvtabular/ops/hash_bucket.py
  nvtabular/ops/lambdaop.py
  nvtabular/ops/normalize.py
  nvtabular/ops/reduce_dtype_size.py
  nvtabular/ops/rename.py
  nvtabular/tools/data_gen.py
  tests/unit/loader/test_torch_dataloader.py
  tests/unit/ops/test_categorify.py
  tests/unit/ops/test_hash_bucket.py
  tests/unit/ops/test_normalize.py
  tests/unit/ops/test_ops.py
  tests/unit/ops/test_ops_schema.py
  tests/unit/ops/test_target_encode.py
  tests/unit/test_s3.py
  tests/unit/workflow/test_workflow.py
  tests/unit/workflow/test_workflow_node.py
Labels: documentation

#1478 README updates
  README.md
  examples/README.md
Labels: documentation
