Repository NVIDIA-Merlin/NVTabular, pull requests merged in 2022-12, with the labels that each got.

#1720 Handle data loader as an iterator
  examples/getting-started-movielens/03-Training-with-PyTorch.ipynb
  examples/getting-started-movielens/03-Training-with-TF.ipynb
  tests/unit/loader/test_torch_dataloader.py
Labels: chore

#1719 Describe how to check for broken links
  docs/README.md
  docs/check_for_broken_links.sh
  docs/false_positives.json
  tox.ini
Labels: skip-changelog, chore

#1724 Address virtual developer review feedback
  README.md
  docs/source/resources/cloud_integration.md
  docs/source/resources/index.rst
  docs/source/resources/support_matrix.rst
Labels: documentation

#1725 Remove echo from command in tox.ini
  tox.ini
Labels: ci

#1723 Use pre-commit for lint checks in GitHub Actions Workflow
  .github/workflows/cpu-ci.yml
  .github/workflows/lint.yaml
  .pre-commit-config.yaml
  requirements/dev.txt
  tox.ini
Labels: ci

#1729 remove integration tests for notebooks no longer available
  tests/integration/common/parsers/benchmark_parsers.py
  tests/integration/common/parsers/criteo_parsers.py
  tests/integration/common/parsers/rossmann_parsers.py
  tests/integration/common/utils.py
  tests/integration/test_criteo.py
  tests/integration/test_movielens.py
  tests/integration/test_nvt_hugectr.py
Labels: ci

#1730 remove test references that are no longer available
  ci/test_integration.sh
Labels: ci

#1727 Update package requires_dist to remove extras that are not required
  requirements/gpu.txt
  setup.py
  tox.ini
Labels: ci

#1734 add transform for df
  nvtabular/workflow/workflow.py
Labels: enhancement

#1728 Add check for urls present in requires_dist
  .github/workflows/cpu-ci.yml
  ci/check_dist.sh
Labels: ci

#1739 adding workflow to setup gha runner for GPU CI
  .github/workflows/gpu-ci.yml
Labels: ci, clean up, chore

#1742 Fix output error occurring due to check if it is a dict or not
  nvtabular/inference/triton/model/model_pt.py
Labels: bug, Inference, P0
