Repository NVIDIA-Merlin/NVTabular, pull requests merged in 2022-05, with the labels that each got.

#1532 Fix getting started 03-Training-with-HugeCTR.ipynb nb's training without printing out auc and loss metrics issue
  examples/getting-started-movielens/03-Training-with-HugeCTR.ipynb
Labels: bug

#1530 remove horovod example, no longer supported
  docs/source/toc.yaml
  examples/multi-gpu-movielens/01-03-MultiGPU-Download-Convert-ETL-with-NVTabular-Training-with-PyTorch.ipynb
  examples/multi-gpu-movielens/README.md
  examples/multi-gpu-movielens/torch_trainer.py
  tests/unit/loader/test_torch_dataloader.py
Labels: bug

#1540 Add release-drafter workflow for generating changelogs
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: ci

#1548 Use common release-drafter workflow
  .github/workflows/release-drafter.yaml
Labels: documentation

#1549 Update changelog to point to github releases
  CHANGELOG.md
Labels: documentation

#1551 Improved docstrings of GroupBy op to reinforce the required usage of dataset.shuffle_by_keys()
  nvtabular/ops/groupby.py
Labels: documentation

#1557 Add conda builds to our github actions workflow
  .github/workflows/cpu-ci.yml
Labels: ci
