Repository NVIDIA-Merlin/NVTabular, pull requests merged in 2023-03, with the labels that each got.

#1782 Fix Dataloader Unittest - which broke by new DL structure
  tests/unit/examples/test_03-Running-on-multiple-GPUs-or-on-CPU.py
  tests/unit/loader/test_tf_dataloader.py
  tests/unit/loader/test_torch_dataloader.py
Labels: ci

#1779 Update default value of `cpu` to None in dataset fixture
  tests/conftest.py
Labels: ci

#1783 Remove tests for sparse tensors in dataloader
  tests/unit/loader/test_tf_dataloader.py
  tests/unit/loader/test_torch_dataloader.py
Labels: ci, chore

#1776 Enable `DatasetGen` usage in CPU environment
  nvtabular/tools/data_gen.py
Labels: bug

#1784 update conftest for backwards compat and new api for to parquet call
  tests/conftest.py
Labels: ci, clean up, chore

#1777 Enable `Workflow.transform` to be run with a DataFrame type
  nvtabular/workflow/workflow.py
  tests/unit/workflow/test_workflow.py
Labels: enhancement

#1775 Fix docs tox environment
  docs/README.md
  tox.ini
Labels: chore

#1780 Split up conda and PyPI package build/release jobs
  .github/workflows/cpu-packages.yml
Labels: ci

#1787 Use None as default value of `cpu` in test_column_similarity
  tests/unit/ops/test_column_similarity.py
Labels: chore

#1788 Use None as default value of cpu in test_torch_dataloader
  tests/unit/loader/test_torch_dataloader.py
Labels: chore

#1774 Workflow syntax error
  .github/workflows/cpu-tests.yml
  .github/workflows/docs-preview-pr.yaml
  .github/workflows/docs-sched-rebuild.yaml
Labels: skip-changelog, chore

#1789 Disable package builds on pull requests
  .github/workflows/cpu-packages.yml
Labels: ci
