Repository NVIDIA-Merlin/NVTabular, pull requests merged in 2023-04, with the labels that each got.

#1795 Replace nvtabular.utils with merlin.core.compat
  examples/03-Running-on-multiple-GPUs-or-on-CPU.ipynb
Labels: ci, chore

#1791 use merlin compat for imports of gpu specific packages
  examples/03-Running-on-multiple-GPUs-or-on-CPU.ipynb
  nvtabular/framework_utils/tensorflow/tfrecords_to_parquet.py
  nvtabular/inference/triton/data_conversions.py
  nvtabular/ops/categorify.py
  nvtabular/ops/column_similarity.py
  nvtabular/ops/join_external.py
  nvtabular/tools/data_gen.py
  nvtabular/utils.py
  nvtabular/workflow/workflow.py
  tests/conftest.py
  tests/unit/examples/test_02-Advanced-NVTabular-workflow.py
  tests/unit/examples/test_03-Running-on-multiple-GPUs-or-on-CPU.py
  tests/unit/loader/test_torch_dataloader.py
  tests/unit/ops/test_categorify.py
  tests/unit/ops/test_drop_low_cardinality.py
  tests/unit/ops/test_groupyby.py
  tests/unit/ops/test_join.py
  tests/unit/ops/test_ops.py
  tests/unit/ops/test_reduce_dtype_size.py
  tests/unit/ops/test_target_encode.py
  tests/unit/test_dask_nvt.py
  tests/unit/test_s3.py
  tests/unit/test_tf4rec.py
  tests/unit/test_triton_inference.py
  tests/unit/workflow/test_cpu_workflow.py
  tests/unit/workflow/test_workflow.py
Labels: enhancement, ci, chore

#1801 add concurrency setting to stop tests when new commits get pushed to PRs
  .github/workflows/cpu-tests.yml
  .github/workflows/gpu-tests.yml
  .github/workflows/lint.yaml
Labels: ci, chore

#1802 Update tox.ini
  tox.ini
Labels: chore
