Repository NVIDIA-Merlin/NVTabular, pull requests merged in 2023-05, with the labels that each got.

#1812 Update tag pattern in GitHub Workflows
  .github/workflows/cpu-packages.yml
  .github/workflows/cpu-tests.yml
  .github/workflows/docs-sched-rebuild.yaml
  .github/workflows/gpu-tests.yml
  .github/workflows/release-drafter.yaml
Labels: ci

#1811 Add workflows to check base branch and set stable branch
  .github/workflows/check-base-branch.yaml
  .github/workflows/set-stable-branch.yaml
Labels: ci

#1813 Remove use of deprecated numpy aliases of builtin types
  nvtabular/ops/column_similarity.py
  nvtabular/ops/target_encoding.py
  tests/unit/loader/test_torch_dataloader.py
Labels: chore

#1805 Update conda package publish for muliple python versions
  .github/workflows/cpu-packages.yml
  conda/recipes/meta.yaml
Labels: chore

#1817 Fix list slicing of `np.ndarray`s on CPU
  nvtabular/ops/list_slice.py
  tests/unit/ops/test_list_slice.py
  tests/unit/ops/test_ops.py
Labels: bug

#1821 Fix API docs
  tox.ini
Labels: skip-changelog, chore

#1822 Remove the `nvtabular.inference` module (deprecated for a long time now)
  nvtabular/inference/__init__.py
  nvtabular/inference/triton/__init__.py
  nvtabular/inference/triton/benchmarking_tools.py
  nvtabular/inference/triton/data_conversions.py
  nvtabular/inference/triton/ensemble.py
  nvtabular/inference/triton/model/__init__.py
  nvtabular/inference/triton/model/model_pt.py
  nvtabular/inference/triton/workflow_model.py
  nvtabular/inference/workflow/__init__.py
  nvtabular/inference/workflow/base.py
  nvtabular/inference/workflow/hugectr.py
  nvtabular/inference/workflow/pytorch.py
  nvtabular/inference/workflow/tensorflow.py
  tests/unit/test_triton_inference.py
Labels: clean up, breaking, chore

#1799 Incorporate `supported_formats` property into NVT ops
  cpp/nvtabular/inference/categorify.cc
  cpp/nvtabular/inference/fill.cc
  nvtabular/ops/normalize.py
  nvtabular/ops/operator.py
Labels: clean up, chore

#1825 aliased stat operator with merlin core stat operator
  nvtabular/ops/stat_operator.py
  nvtabular/workflow/workflow.py
Labels: bug

#1692 Refactor Categorify
  bench/examples/MultiGPUBench.md
  bench/examples/dask-nvtabular-criteo-benchmark.py
  cpp/nvtabular/inference/categorify.cc
  nvtabular/ops/categorify.py
  nvtabular/ops/drop_low_cardinality.py
  nvtabular/ops/join_groupby.py
  nvtabular/ops/target_encoding.py
  tests/unit/ops/test_categorify.py
  tests/unit/ops/test_drop_low_cardinality.py
  tests/unit/workflow/test_cpu_workflow.py
  tests/unit/workflow/test_workflow.py
Labels: enhancement, MultiGPU, ops
