Repository NVIDIA-Merlin/NVTabular, pull requests merged in 2023-06, with the labels that each got.

#1824 adding ops-bot yaml file
  .github/ops-bot.yaml
Labels: ci

#1831 Update Notebook Example to correctly extract visible devices
  examples/03-Running-on-multiple-GPUs-or-on-CPU.ipynb
Labels: ci

#1834 Add ops module import to nvtabular
  nvtabular/__init__.py
Labels: chore

#1833 Pass keyword argument for axis in dataframe any method
  nvtabular/ops/categorify.py
Labels: chore

#1832 Use tmpdir for Categorify out_path in test_tf4rec
  tests/unit/test_tf4rec.py
Labels: ci

#1836 Update nulls in categorify encode to array instead of index value
  nvtabular/ops/categorify.py
Labels: ci

#1835 Remove `n_workers=2` from Distributed in client fixture
  tests/conftest.py
Labels: ci

#1827 How to for embedding op with categorify from scratch
  tests/unit/workflow/test_workflow.py
Labels: enhancement

#1842 working subgraphs in workflow
  nvtabular/workflow/workflow.py
  tests/unit/workflow/test_workflow_subgraphs.py
Labels: enhancement

#1847 Update merlin dependency versions to match 23.06 release
  requirements/base.txt
Labels: chore, skip-base-branch-check

#1854 fix the workflow node tests on additions in graph
  tests/unit/workflow/test_workflow_node.py
Labels: bug
