Repository NVIDIA-Merlin/NVTabular, pull requests merged in 2023-02, with the labels that each got.

#1758 Update NVT to be compatible with shapes in `ColumnSchemas`
  nvtabular/loader/backend.py
  nvtabular/ops/list_slice.py
  tests/unit/ops/test_value_count.py
Labels: clean up, chore

#1732 Specify Minimum Python Version as 3.8 in package
  setup.py
Labels: ci

#1757 Fix the inference code's deprecation warning
  nvtabular/inference/__init__.py
Labels: clean up, chore

#1762 Update passenv in test-gpu to use valid configuration
  tox.ini
Labels: ci

#1760 Clean up the way shapes are computed and specified
  nvtabular/loader/backend.py
  nvtabular/loader/tensorflow.py
  nvtabular/ops/groupby.py
  nvtabular/ops/join_groupby.py
  nvtabular/ops/list_slice.py
  nvtabular/ops/value_counts.py
  tests/unit/ops/test_ops_schema.py
Labels: clean up, chore

#1741 Add support for serializing modules involved in LambdaOp execution by value
  nvtabular/workflow/workflow.py
  tests/unit/workflow/test_workflow.py
Labels: bug

#1765 docs: Rebuild on push
  .github/workflows/docs-sched-rebuild.yaml
  docs/README.md
Labels: skip-changelog, chore
